requires 'AnyEvent::HTTP';
requires 'AnyEvent::Handle';
requires 'JSON::XS';
requires 'Log::Any';
requires 'Log::Any::Adapter';
requires 'Log::Dispatch';
requires 'Message::Passing::ZeroMQ';
requires 'Mojolicious', '>= 4.60';
requires 'Term::ANSIColor';
requires 'YAML::XS';
requires 'common::sense';
